[tools]
claude = "latest"
python = "latest"
go = "latest"
java = "corretto-23"
lazydocker = "latest"
node = "lts"
pnpm = "latest"
ruby = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
